### ISSUE TITLE
Taking a break for more than 251 minutes by calling `coffee_break!` for multiple times

### ISSUE THREAD

**Issue by ActiveTK** [radekvit/coffee_break#1]

**Comment by ActiveTK** [comment]
In spite of there are some limits of break time, we can take a break for more than 251 minutes by calling `coffee_break!` for multiple times.

Here is a example:
```Rust
fn work_stuff() {
    // I can take a break for  250 minutes × 100 ~ 416 hours
    for n in 1..100 {
        coffee_break!(250  minutes);
    }
}
```

**Comment by ActiveTK** [comment]
I'm sorry for not providing a description of the issue. I'll rewrite it.

**Comment by radekvit** [comment]
You can take a longer break by adding multiple coffee breaks, but that's allowed. It won't add a longer break with your code though, that's still just a single 250 minute break
